const PDFDocument = require("pdfkit");

// ── Design tokens ─────────────────────────────────────────────────────────────
const C = {
  navy:    "#1e3a5f",
  blue:    "#2563eb",
  bgLight: "#f1f5f9",
  bgAlt:   "#f8fafc",
  border:  "#cbd5e1",
  text:    "#1e293b",
  muted:   "#64748b",
  red:     "#dc2626",
  amber:   "#d97706",
  green:   "#16a34a",
  white:   "#ffffff",
};

const FONT   = { regular: "Helvetica", bold: "Helvetica-Bold" };
const MARGIN = 50;
const PW     = 595 - MARGIN * 2; // printable width on A4

// ── Low-level helpers ─────────────────────────────────────────────────────────

const hRule = (doc, y, color = C.border) => {
  doc.moveTo(MARGIN, y).lineTo(MARGIN + PW, y)
     .strokeColor(color).lineWidth(0.5).stroke();
  return y;
};

const sectionTitle = (doc, y, title) => {
  doc.rect(MARGIN, y, PW, 20).fill(C.navy);
  doc.font(FONT.bold).fontSize(9).fillColor(C.white)
     .text(title.toUpperCase(), MARGIN + 8, y + 6, { width: PW - 16 });
  return y + 20;
};

const labelValue = (doc, x, y, label, value, { labelWidth = 110 } = {}) => {
  doc.font(FONT.bold).fontSize(8).fillColor(C.muted)
     .text(label, x, y, { width: labelWidth });
  doc.font(FONT.regular).fontSize(8).fillColor(C.text)
     .text(String(value ?? "Not recorded"), x + labelWidth, y, { width: PW / 2 - labelWidth });
};

/**
 * Draws a table with shaded header and alternating row backgrounds.
 * Cells can be plain strings or { text, color } objects for coloured text.
 * Returns the Y position after the last row.
 */
const drawTable = (doc, y, { headers, rows, colWidths, rowHeight = 22, headerHeight = 26 }) => {
  const totalW = colWidths.reduce((a, b) => a + b, 0);

  // Header row
  doc.rect(MARGIN, y, totalW, headerHeight).fill(C.bgLight);
  let cx = MARGIN;
  headers.forEach((h, i) => {
    doc.font(FONT.bold).fontSize(8).fillColor(C.text)
       .text(h, cx + 6, y + Math.floor((headerHeight - 8) / 2), {
         width: colWidths[i] - 8, lineBreak: false,
       });
    cx += colWidths[i];
  });

  // Data rows
  rows.forEach((row, ri) => {
    const ry = y + headerHeight + ri * rowHeight;
    if (ri % 2 === 0) {
      doc.rect(MARGIN, ry, totalW, rowHeight).fill(C.bgAlt);
    }
    let cx = MARGIN;
    row.forEach((cell, ci) => {
      const text  = typeof cell === "object" ? (cell?.text ?? "—") : String(cell ?? "—");
      const color = typeof cell === "object" ? (cell?.color ?? C.text) : C.text;
      doc.font(FONT.regular).fontSize(7.5).fillColor(color)
         .text(text, cx + 6, ry + Math.floor((rowHeight - 7.5) / 2), {
           width: colWidths[ci] - 8, lineBreak: false,
         });
      cx += colWidths[ci];
    });
  });

  // Outer border
  doc.rect(MARGIN, y, totalW, headerHeight + rows.length * rowHeight)
     .strokeColor(C.border).lineWidth(0.5).stroke();

  // Column dividers
  cx = MARGIN;
  colWidths.slice(0, -1).forEach((w) => {
    cx += w;
    doc.moveTo(cx, y).lineTo(cx, y + headerHeight + rows.length * rowHeight)
       .strokeColor(C.border).lineWidth(0.3).stroke();
  });

  // Row dividers
  for (let ri = 0; ri <= rows.length; ri++) {
    const ry = y + headerHeight + ri * rowHeight;
    doc.moveTo(MARGIN, ry).lineTo(MARGIN + totalW, ry)
       .strokeColor(C.border).lineWidth(0.3).stroke();
  }

  return y + headerHeight + rows.length * rowHeight;
};

// ── Formatters ────────────────────────────────────────────────────────────────
const fDate = (d) =>
  d ? new Date(d).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "—";

const fDateTime = (d) =>
  d ? new Date(d).toLocaleString("en-IN", {
    day: "2-digit", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit",
  }) : "—";

const severityColor = (s) =>
  ({ severe: C.red, moderate: C.amber, mild: C.green }[s] ?? C.muted);

// ── Repeated page chrome ──────────────────────────────────────────────────────

const pageHeader = (doc, hospitalName) => {
  doc.rect(0, 0, 595, 48).fill(C.navy);
  doc.font(FONT.bold).fontSize(16).fillColor(C.white)
     .text("Swasthify", MARGIN, 14);
  doc.font(FONT.regular).fontSize(8).fillColor("#93c5fd")
     .text("Multi-Hospital Patient Record Network", MARGIN, 32);
  if (hospitalName) {
    doc.font(FONT.regular).fontSize(8).fillColor(C.white)
       .text(hospitalName, 0, 18, { align: "right", width: 595 - MARGIN });
  }
  return 62;
};

const pageFooter = (doc, pageNum) => {
  const y = 800;
  hRule(doc, y);
  doc.font(FONT.regular).fontSize(6.5).fillColor(C.muted)
     .text(
       "DISCLAIMER: This document is generated by Swasthify for use by qualified healthcare professionals only. " +
       "It does not constitute a medical diagnosis or prescription. Always exercise clinical judgment.",
       MARGIN, y + 6, { width: PW - 50 }
     );
  doc.font(FONT.regular).fontSize(7).fillColor(C.muted)
     .text(`Page ${pageNum}`, 0, y + 6, { align: "right", width: 595 - MARGIN });
};

// ═════════════════════════════════════════════════════════════════════════════
// Report 1 — Patient Summary
// Demographics + latest vitals + vitals averages + medical history + appointments
// ═════════════════════════════════════════════════════════════════════════════

const buildPatientSummary = (doc, {
  patient, demographics, latestVitals,
  vitalsSummary, medicalHistory, appointments,
  generatedBy, hospitalName,
}) => {
  let y      = pageHeader(doc, hospitalName);
  let pageNum = 1;

  // Report title
  y += 14;
  doc.font(FONT.bold).fontSize(14).fillColor(C.navy)
     .text("Patient Medical Summary Report", MARGIN, y);
  doc.font(FONT.regular).fontSize(8).fillColor(C.muted)
     .text(
       `Generated: ${fDateTime(new Date())}   ·   Prepared by: ${generatedBy}`,
       MARGIN, y + 18
     );
  y += 38;
  hRule(doc, y);
  y += 14;

  // ── 1. Demographics ──────────────────────────────────────────────────────
  y = sectionTitle(doc, y, "Patient Information");
  y += 10;

  const col1 = MARGIN;
  const col2 = MARGIN + PW / 2;

  labelValue(doc, col1, y,       "Patient ID:",          patient.patientID);
  labelValue(doc, col2, y,       "Blood Group:",         patient.bloodGroup ?? "Not recorded");
  y += 16;
  labelValue(doc, col1, y,       "Full Name:",           patient.name);
  labelValue(doc, col2, y,       "Gender:",              patient.gender ?? "Not recorded");
  y += 16;
  labelValue(doc, col1, y,       "Date of Birth:",       fDate(patient.dob));
  labelValue(doc, col2, y,       "Age:",                 `${demographics.age} years`);
  y += 16;
  labelValue(doc, col1, y,       "Phone:",               patient.phone ?? "Not recorded");
  labelValue(doc, col2, y,       "Emergency Contact:",   patient.emergencyContact ?? "Not recorded");
  y += 20;
  hRule(doc, y);
  y += 14;

  // ── 2. Latest Vitals ─────────────────────────────────────────────────────
  y = sectionTitle(doc, y, "Latest Vitals Reading");
  y += 10;

  if (latestVitals) {
    doc.font(FONT.regular).fontSize(8).fillColor(C.muted)
       .text(
         `Recorded: ${fDateTime(latestVitals.recordedAt)}   ·   By: ${latestVitals.recordedBy?.name ?? "—"}   ·   ${latestVitals.hospital?.name ?? ""}`,
         MARGIN, y
       );
    y += 14;

    const half = 3;
    const vCols = [
      ["Blood Pressure",   `${latestVitals.bpSystolic}/${latestVitals.bpDiastolic} mmHg`],
      ["Heart Rate",       `${latestVitals.heartRate} bpm`],
      ["Blood Sugar",      `${latestVitals.sugar} mg/dL`],
      ["SpO₂",            latestVitals.spo2        != null ? `${latestVitals.spo2}%`    : "Not recorded"],
      ["Temperature",      latestVitals.temperature != null ? `${latestVitals.temperature}°C` : "Not recorded"],
      ["Weight",           latestVitals.weight      != null ? `${latestVitals.weight} kg` : "Not recorded"],
    ];
    vCols.slice(0, half).forEach(([l, v], i) => labelValue(doc, col1, y + i * 16, l + ":", v));
    vCols.slice(half).forEach(([l, v], i)    => labelValue(doc, col2, y + i * 16, l + ":", v));
    y += half * 16 + 10;

    // Averages row
    if (vitalsSummary?.totalReadings > 1) {
      const avg = vitalsSummary.averages;
      y += 6;
      doc.font(FONT.bold).fontSize(8).fillColor(C.text)
         .text(`Averages across ${vitalsSummary.totalReadings} readings:`, MARGIN, y);
      y += 12;
      y = drawTable(doc, y, {
        headers:   ["Avg BP (mmHg)", "Avg HR (bpm)", "Avg Sugar (mg/dL)", "Avg SpO₂ (%)", "Avg Temp (°C)"],
        rows: [[
          `${avg.bpSystolic ?? "—"}/${avg.bpDiastolic ?? "—"}`,
          avg.heartRate    ?? "—",
          avg.sugar        ?? "—",
          avg.spo2         ?? "—",
          avg.temperature  ?? "—",
        ]],
        colWidths: Array(5).fill(PW / 5),
        rowHeight: 22,
      });
      y += 4;
    }
  } else {
    doc.font(FONT.regular).fontSize(8).fillColor(C.muted)
       .text("No vitals recorded yet.", MARGIN, y);
    y += 18;
  }

  y += 10;
  hRule(doc, y);
  y += 14;

  // ── 3. Medical History ────────────────────────────────────────────────────
  if (y + 26 + Math.min(medicalHistory.length, 5) * 22 > 760) {
    pageFooter(doc, pageNum++);
    doc.addPage();
    y = pageHeader(doc, hospitalName) + 14;
  }

  y = sectionTitle(doc, y, `Medical History   (${medicalHistory.length} records)`);
  y += 10;

  if (medicalHistory.length === 0) {
    doc.font(FONT.regular).fontSize(8).fillColor(C.muted)
       .text("No medical history recorded.", MARGIN, y);
    y += 18;
  } else {
    const histRows = medicalHistory.map((h) => [
      fDate(h.occurredAt),
      h.type.replace("_", " ").toUpperCase(),
      h.title,
      h.description.length > 55 ? h.description.slice(0, 52) + "..." : h.description,
      { text: h.severity ?? "—", color: severityColor(h.severity) },
      h.hospital?.name ?? "—",
    ]);

    // Paginate if needed
    const ROWS_PER_PAGE = 24;
    for (let ci = 0; ci < histRows.length; ci += ROWS_PER_PAGE) {
      if (ci > 0) {
        pageFooter(doc, pageNum++);
        doc.addPage();
        y = pageHeader(doc, hospitalName) + 14;
      }
      y = drawTable(doc, y, {
        headers:   ["Date", "Type", "Title", "Description", "Severity", "Hospital"],
        rows:      histRows.slice(ci, ci + ROWS_PER_PAGE),
        colWidths: [65, 75, 100, 145, 55, 55],
        rowHeight: 22,
      });
      y += 4;
    }
  }

  y += 10;
  hRule(doc, y);
  y += 14;

  // ── 4. Appointments ────────────────────────────────────────────────────────
  if (y + 26 + Math.min(appointments.length, 3) * 22 > 760) {
    pageFooter(doc, pageNum++);
    doc.addPage();
    y = pageHeader(doc, hospitalName) + 14;
  }

  y = sectionTitle(doc, y, `Upcoming Appointments   (${appointments.length})`);
  y += 10;

  if (appointments.length === 0) {
    doc.font(FONT.regular).fontSize(8).fillColor(C.muted)
       .text("No upcoming appointments.", MARGIN, y);
    y += 18;
  } else {
    y = drawTable(doc, y, {
      headers:   ["Scheduled At", "Doctor", "Status", "Reason", "Hospital"],
      rows:      appointments.map((a) => [
        fDateTime(a.scheduledAt),
        a.staff?.name ?? "—",
        a.status.toUpperCase(),
        a.reason ?? "—",
        a.hospital?.name ?? "—",
      ]),
      colWidths: [130, 100, 70, 130, 65],
      rowHeight: 22,
    });
  }

  pageFooter(doc, pageNum);
};

// ═════════════════════════════════════════════════════════════════════════════
// Report 2 — Vitals History (full time-series export)
// ═════════════════════════════════════════════════════════════════════════════

const buildVitalsHistory = (doc, { patient, readings, from, to, generatedBy, hospitalName }) => {
  let y       = pageHeader(doc, hospitalName);
  let pageNum = 1;

  y += 14;
  doc.font(FONT.bold).fontSize(14).fillColor(C.navy)
     .text("Vitals History Report", MARGIN, y);
  doc.font(FONT.regular).fontSize(8).fillColor(C.muted)
     .text(
       `Patient: ${patient.name} (${patient.patientID})   ·   ` +
       `Period: ${from ? fDate(from) : "All time"} – ${to ? fDate(to) : "Present"}   ·   ` +
       `Total readings: ${readings.length}   ·   Generated: ${fDateTime(new Date())}   ·   By: ${generatedBy}`,
       MARGIN, y + 18, { width: PW }
     );
  y += 42;
  hRule(doc, y);
  y += 14;

  if (readings.length === 0) {
    doc.font(FONT.regular).fontSize(10).fillColor(C.muted)
       .text("No vitals recorded for the selected period.", MARGIN, y);
    pageFooter(doc, pageNum);
    return;
  }

  const ROWS_PER_PAGE = 28;
  const chunks = [];
  for (let i = 0; i < readings.length; i += ROWS_PER_PAGE) {
    chunks.push(readings.slice(i, i + ROWS_PER_PAGE));
  }

  chunks.forEach((chunk, ci) => {
    if (ci > 0) {
      pageFooter(doc, pageNum++);
      doc.addPage();
      y = pageHeader(doc, hospitalName) + 20;
    }

    y = drawTable(doc, y, {
      headers:   ["Recorded At", "BP (mmHg)", "HR (bpm)", "Sugar (mg/dL)", "SpO₂ (%)", "Temp (°C)", "Weight (kg)", "Hospital"],
      rows:      chunk.map((r) => [
        fDateTime(r.recordedAt),
        `${r.bpSystolic}/${r.bpDiastolic}`,
        r.heartRate,
        r.sugar,
        r.spo2        ?? "—",
        r.temperature ?? "—",
        r.weight      ?? "—",
        r.hospital?.name ?? "—",
      ]),
      colWidths: [115, 65, 55, 75, 55, 55, 65, 60],
      rowHeight: 20,
    });
    y += 8;
  });

  pageFooter(doc, pageNum);
};

// ── Public API ────────────────────────────────────────────────────────────────

const createDoc = () =>
  new PDFDocument({ margin: MARGIN, size: "A4", autoFirstPage: true });

module.exports = { createDoc, buildPatientSummary, buildVitalsHistory };